name: 'Automatic Flow'

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Using Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 20.x
            - name: Install & Build
              run: |
                  npm init